build:
  image: node:4
  commands:
    - ls
    - npm install --no-progress --color --quiet
    - "npm start &"
    - npm run ci --no-progress --color

compose:
  selenium:
    image: selenium/standalone-chrome
clone:
  depth: 10
cache:
  mount:
    - node_modules
    - .git
environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
